/* ─── Placeholder data — will be replaced with Supabase queries ─── */

export const PLACEHOLDER_IMAGES = [
  'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop&q=80',
]

export const PLACEHOLDER_PROPERTIES = [
  {
    slug: 'atico-centro',
    title: 'Ático con terraza en el centro',
    location: 'Centro, Madrid',
    price: 425000,
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    image: PLACEHOLDER_IMAGES[0],
    status: 'available' as const,
    category: 'resale' as const,
  },
  {
    slug: 'villa-costa',
    title: 'Villa moderna con piscina',
    location: 'Costa del Sol, Málaga',
    price: 890000,
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    image: PLACEHOLDER_IMAGES[1],
    status: 'available' as const,
    category: 'newBuild' as const,
  },
  {
    slug: 'piso-playa',
    title: 'Piso a 100m de la playa',
    location: 'Benidorm, Alicante',
    price: 195000,
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    image: PLACEHOLDER_IMAGES[2],
    status: 'reserved' as const,
    category: 'resale' as const,
  },
  {
    slug: 'duplex-norte',
    title: 'Dúplex con vistas a la montaña',
    location: 'Santander, Cantabria',
    price: 310000,
    bedrooms: 3,
    bathrooms: 2,
    area: 145,
    image: PLACEHOLDER_IMAGES[0],
    status: 'available' as const,
    category: 'newBuild' as const,
  },
  {
    slug: 'estudio-universidad',
    title: 'Estudio reformado zona universitaria',
    location: 'Salamanca',
    price: 95000,
    bedrooms: 1,
    bathrooms: 1,
    area: 38,
    image: PLACEHOLDER_IMAGES[1],
    status: 'available' as const,
    category: 'resale' as const,
  },
  {
    slug: 'adosado-parque',
    title: 'Adosado junto al parque',
    location: 'Pozuelo, Madrid',
    price: 520000,
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    image: PLACEHOLDER_IMAGES[2],
    status: 'available' as const,
    category: 'newBuild' as const,
  },
]
